learner:
  alg: MC
  env: GuanDan
  data_port: 5002
  param_port: 5001
  model: guandan_model
  pool_size: 65536
  batch_size: 32768
  training_freq: 250
  keep_training: false
  record_throughput_interval: 1000
  num_envs: 1
  ckpt_save_freq: 3000
  ckpt_save_type: weight
  observation_space: !!python/tuple
    - 567
  action_space: !!python/tuple
    - 5
    - 216
  epsilon: 0.01

agent:
  lr: 0.001
  model:
    model_id: '0'
